name: Test React
on:
  push:
    branches:
      - feat/feat_dockeractions
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t moient/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true moient/react-test npm test
        working-directory: ./frontend