name: Deploy Frontend
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Build and test the dev image
      - name: Build dev Image
        run: docker build -t moeint/react-test -f Dockerfile.dev .

      - name: Run Tests on dev
        run: docker run -e CI=true moeint/react-test npm test

      # Build and push the prod image
      - name: Build prod Image
        run: docker build . -t ${{ secrets.DOCKER_USERNAME }}/react-prod:first-ctr

      - name: Push to Dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/react-prod:first-ctr

      # Deploy to AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-west-3

      - name: Deploy to AWS Elastic Beanstalk
        uses: aws-actions/elastic-beanstalk-deploy@v1
        with:
          application-name: docker-react-tf
          environment-name: docker-react-tf-env
          version-label: ${{ github.sha }}
          package: ${{ secrets.DOCKER_USERNAME }}/react-prod:first-ctr


# Add a step for EBS to download the image and deploy it.

      # - name: Generate deployment package
      #   run: zip -r deploy.zip ./ -x '*.git*'


      # - name: Deploy to EB
      #   uses: einaregilsson/beanstalk-deploy@v18
      #   with:
      #     aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
      #     aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
      #     application_name: docker-react-tf
      #     environment_name: docker-react-tf-env
      #     existing_bucket_name: elasticbeanstalk-eu-west-3-651778762109
      #     region: eu-west-3
      #     version_label: ${{ github.sha }}
      #     deployment_package: ./frontend/deploy.zip