name: Test React
on:
  push:
    branches:
      - feat/feat_dockeractions
 
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Dockerhub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: docker build -t moient/react-test -f Dockerfile.dev .
      - name: Run tests
        run: docker run -e CI=true moient/react-test npm test